//! Hash algorithms supported for Artifact IDs.
//!
//! Currently, OmniBOR only supports one hash algorithm, SHA-256, as the basis
//! for creating Artifact IDs and Input Manifests. If, in the future, SHA-256's
//! cryptographic properties are broken, then OmniBOR may migrate to an
//! alternative hash function.
//!
//! This module contains the [`HashAlgorithm`] trait and the [`Sha256`] type.
//! The trait represents hash algorithms available for use in OmniBOR, and
//! [`Sha256`] is the only type that implements the trait.
//!
//! Much of the generic code in the `omnibor` crate relies on the [`Sha256`]
//! type.

use {
    crate::util::sealed::Sealed,
    digest::{
        consts::U32,
        generic_array::{sequence::GenericSequence, GenericArray},
    },
    std::{fmt::Debug, ops::Deref},
};

#[cfg(doc)]
use crate::ArtifactId;

/// Marker trait for hash algorithms supported for constructing [`ArtifactId`]s.
///
/// This trait is sealed, meaning it can only be implemented within the
/// `omnibor` crate.
pub trait HashAlgorithm: Sealed {
    /// The name of the hash algorithm, to be written in the GitOid string.
    #[doc(hidden)]
    const NAME: &'static str;

    /// The array type generated by the hash.
    #[doc(hidden)]
    type Array: GenericSequence<u8>
        + FromIterator<u8>
        + Deref<Target = [u8]>
        + PartialEq
        + Eq
        + Clone
        + Copy
        + Debug;
}

/// Use SHA-256 as the hash algorithm.
pub struct Sha256 {
    #[doc(hidden)]
    _private: (),
}

impl Sealed for Sha256 {}

impl HashAlgorithm for Sha256 {
    const NAME: &'static str = "sha256";

    // A SHA-256 hash is 32 bytes long.
    type Array = GenericArray<u8, U32>;
}
